language: node_js
node_js:
- '4.0'
- '7.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: 0y8jHVrLfT/rsZ0FPQqstJG6uC67GCBC+Io9xEOX2R1hzkQyNoCWKLPnmwUu+a1ArrZfoLOtgKDjsTsHXeuVGD/MAQcLp/ME8OJJtzg8DB3sqb4D5i+U0mODRMwoCN4J0FJBETtd8zddgEyKXPsg50GtvhSuvS4siZ0zhAW5ghi5AuX9ExJO9gk8GfaYHXw27CfJkBes6jbDgPEuQxpAjdOUAW7OX1dCsWXZHVxw0htZfFCu3ssglJ6qKvdtgKpqLO62G02F1vVBliW5CPeK27zHsrMvbE9lb+5pwwNfHEUA5ldD/b5kw9o5DMvU/m2p+51B/PokYe1qYbdsm8/slB+QxkUNHnAOGL9XYlr8qlVbRNM//FfE0yNRD21Gvq/4DjuHLvjZ1TwY80TY4uQ9B16Wx83WUD4jn4V4KaLENKEz6AO+iTc5WrvoLmBT+sEqvZYnueaFzH+xqTGDOUrwzV4N49CJGZoYhUAgEs4K1w2gJH0kIWr/utpYWrpa+wlpBV7hB/Kbhk2T1C0MVzvcPP29/4dB8yMc1AtoeJCQMSQdUPOo4Qbs5QP/jM2ECzW3GuOFkifV+B4eZrEgzN00HGtcQ9Y+pCzzt6BpI6GcFB/UpW210KnPa1cavc49oua39NAdFVUhF4+gT9xlBluAGfP1m8Xla9DV0Zbiil6EAP0=
    on:
      tags: true
      node: '4.0'
  - provider: releases
    api_key:
      secure: EZ9UfpuzdtZtKn8Ri7rKQq3isLuhCJfPFhUtWNUi3mS99VJKR2dnhRGG+5ncEIgE0PRugVPc7Cyqv8XWryEf1MmyuWCHQBTfKrBBJT1rjcqbgt0wLqcSAgMFsUGeYlOr9CdUhed8/YaKEtINVBq7oILLhHFlHuTkSDx+1uHhB/WzwF/TlJ3Ond/bNCLE+qln5nBIkLZas97VIKEy5cPLIeYGRZ4B4MOYn0tUz0ZctGzuzMa1Jtl1+2t+zaNa5kYZ8DPXRd7tAw4lay3jAckbrr/WqAFq10SzOgdt3KvSnAWxJdxL9EXMFDJd8+2MMZQSwiIvI0BYisi4HLLSMgyRcKg4IW0NL0y65SXQLeS1V5pqU7V3xBWLP5NJw80JyqHUpO3wzgYExmmS+qtU5/qtbzzbMug9IBHUx6nCCcLG+vd2HaRWDCVZHFsM7laUdgw/28Y+1yDp+Zx1s7KXsGVveUqy1moDVKCB0jV/ckinN7cLT4Kpcw5rScffR4hM1R+tgmTwQXMLykZkQtej/GKD6HMruytxaZQHVG6Q+23NF93+X8UNEwv8ORCXHwfLJjmCZA/eYJuTD9cyQC1O06Cof7mCRlDHDiMo68gfn90pB7GIsE7rq8v+rkLJQ9n7tZ4hlAchEFF6ejI8q/DYhTM4xc5eT29vRd6xnI/6gqe0A7s=
    file:
      - "rehype-remark.js"
      - "rehype-remark.min.js"
    on:
      tags: true
      node: '7.0'
